[tool.poetry]
name = "squareworld"
version = "0.1.0"
description = ""
authors = ["afonsomedeiros <afonso.b.medeiros@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygame = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
